title: Jalapeño
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An unconference by JConfMexico focusing on JVM and modern JVM technologies.
additional_info: >-
  September 14 & 15, 2024
# baseurl: "jalapeño" # the subpath of your site, e.g. /blog
# url: "https://jconfmexico.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JalapenoUnconf
github_username:  JConfMexico
social_username: jconfmexico

# Build settings
# theme: minima
remote_theme: broccolini/swiss
# Navigation
# nav:
  # - text: Home
    # url: /
  # - text: Code of Conduct
    # url: /code-of-conduct

# permalink: /:title/

# Sass settings
sass:
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor

